services:
  bot:
    image: ghcr.io/igoof14/t-invest-bot:latest
    container_name: t-invest-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@${DB_HOST}:5432/tinvest
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
